/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    {
      type: "doc",
      label: "Overview",
      id: "overview/overview",
    },
    {
      type: "category",
      label: "Quickstart",
      link: {
        type: "doc",
        id: "quickstart/quickstart",
      },
      collapsed: true,
      items: [
        {
          type: "doc",
          label: "Quickstart: TypeScript",
          id: "quickstart/quickstart",
        },
        {
          type: "doc",
          label: "Quickstart: Go",
          id: "quickstart/quickstart-go",
        },
        {
          type: "doc",
          label: "Quickstart: Java",
          id: "quickstart/quickstart-java",
        },
        {
          type: "doc",
          label: "Quickstart: HTTP",
          id: "quickstart/quickstart-http",
        },
      ],
    },
    "overview/architecture",
    {
      type: "category",
      label: "Database",
      link: {
        type: "doc",
        id: "database/database",
      },
      collapsed: true,
      items: [
        "database/documents",
        "database/datamodel",
        "database/schema-validation",
        "database/schema-modification",
        "database/crud",
        "database/search",
        "database/transaction",
        "database/filters",
        "database/restrictions",
      ],
    },
    {
      type: "doc",
      label: "Search",
      id: "searching/search",
    },
    {
      type: "category",
      label: "Platform",
      link: {
        type: "doc",
        id: "platform/platform",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Metrics and Tracing",
          link: {
            type: "doc",
            id: "platform/metrics",
          },
          collapsed: true,
          items: ["platform/metrics-tags"],
        },
        "platform/auth/auth",
        {
          type: "category",
          label: "Self-host",
          link: {
            type: "doc",
            id: "platform/self-host/self-host",
          },
          collapsed: true,
          items: [
            "platform/self-host/deploy-tigris-on-eks",
            "platform/self-host/deploy-tigris-on-gke",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "TypeScript Reference",
      link: {
        type: "doc",
        id: "typescript/index",
      },
      collapsed: true,
      items: [
        "typescript/getting-started",
        {
          type: "category",
          label: "Database",
          link: {
            type: "doc",
            id: "typescript/database/index",
          },
          collapsed: false,
          items: [
            "typescript/database/datamodel",
            "typescript/database/types",
            "typescript/database/schema",
            "typescript/database/schema-bootstrap",
            "typescript/database/insert",
            "typescript/database/update",
            "typescript/database/delete",
            "typescript/database/query",
            "typescript/database/search",
            "typescript/database/transactions",
            "typescript/database/cursor",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Go Reference",
      link: {
        type: "doc",
        id: "golang/index",
      },
      collapsed: true,
      items: [
        "golang/getting-started",
        {
          type: "category",
          label: "Database",
          link: {
            type: "doc",
            id: "golang/database/documents",
          },
          collapsed: false,
          items: [
            "golang/database/datamodel",
            "golang/database/types",
            "golang/database/schema",
            "golang/database/insert",
            "golang/database/update",
            "golang/database/delete",
            "golang/database/query",
            "golang/database/search",
            "golang/database/transactions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Java Reference",
      link: {
        type: "doc",
        id: "java/getting-started",
      },
      collapsed: true,
      items: [
        "java/getting-started",
        {
          type: "category",
          label: "Database",
          link: {
            type: "doc",
            id: "java/database/index",
          },
          collapsed: false,
          items: [
            {
              type: "category",
              label: "Data Modeling",
              link: {
                type: "doc",
                id: "java/database/datamodel/overview",
              },
              collapsed: false,
              items: [
                "java/database/datamodel/declare",
                "java/database/datamodel/primary-key",
                "java/database/datamodel/embedded",
                "java/database/datamodel/types",
              ],
            },
            "java/database/insert",
            "java/database/update",
            "java/database/delete",
            "java/database/query",
            "java/database/search",
            "java/database/transactions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "HTTP Reference",
      collapsed: true,
      link: {
        type: "doc",
        id: "http/index",
      },
      items: [
        "http/getting-started",
        {
          type: "category",
          label: "Data Modeling",
          link: {
            type: "doc",
            id: "http/datamodel/overview",
          },
          collapsed: false,
          items: [
            "http/datamodel/declare",
            "http/datamodel/primary-key",
            "http/datamodel/embedded",
            "http/datamodel/types",
          ],
        },
        "http/insert",
        "http/update",
        "http/delete",
        "http/query",
        "http/search",
      ],
    },
    {
      type: "category",
      label: "Command Line Interface",
      link: {
        type: "doc",
        id: "cli/overview",
      },
      collapsed: true,
      items: [
        "cli/authentication",
        "cli/installation",
        "cli/configuration",
        "cli/working-locally",
        {
          type: "category",
          label: "Reference",
          items: [
            "cli/reference/alter-application",
            "cli/reference/alter-collection",
            "cli/reference/completion",
            "cli/reference/config-show",
            "cli/reference/create-application",
            "cli/reference/create-collection",
            "cli/reference/create-project",
            "cli/reference/delete",
            "cli/reference/describe-collection",
            "cli/reference/describe-database",
            "cli/reference/dev-logs",
            "cli/reference/dev-start",
            "cli/reference/dev-stop",
            "cli/reference/drop-application",
            "cli/reference/drop-collection",
            "cli/reference/delete-project",
            "cli/reference/generate-sample-schema",
            "cli/reference/insert",
            "cli/reference/list-applications",
            "cli/reference/list-collections",
            "cli/reference/list-projects",
            "cli/reference/login",
            "cli/reference/logout",
            "cli/reference/ping",
            "cli/reference/read",
            "cli/reference/replace",
            "cli/reference/scaffold-go",
            "cli/reference/search",
            "cli/reference/server-info",
            "cli/reference/server-version",
            "cli/reference/transact",
            "cli/reference/update",
            "cli/reference/version",
          ],
        },
      ],
    },
    {
      type: "doc",
      label: "Create Tigris App",
      id: "create-tigris-app/create-tigris-app",
    },
  ],
  guides: [
    {
      type: "category",
      label: "Next.js",
      link: {
        type: "doc",
        id: "guides/nextjs/index",
      },
      collapsed: false,
      items: ["guides/nextjs/add-existing-app/index"],
    },
    {
      type: "category",
      label: "Deploying Apps built with Tigris",
      collapsed: false,
      items: [
        "guides/deploy-tigris-app/deploy-to-vercel/index",
        "guides/deploy-tigris-app/deploy-to-netlify/index",
      ],
    },
    {
      type: "category",
      label: "Nuxt.js",
      link: {
        type: "doc",
        id: "guides/nuxtjs/index",
      },
      collapsed: false,
      items: ["guides/nuxtjs/ecommerce/index"],
    },
    {
      type: "doc",
      id: "guides/rest-webapp-typescript",
    },
    {
      type: "doc",
      id: "guides/rest-webapp-go",
    },
    {
      type: "doc",
      id: "guides/rest-webapp-java",
    },
  ],
};

module.exports = sidebars;
